### ISSUE TITLE
Crash when REI attempts to load an item (I think the patchouli book)

### ISSUE THREAD

**Issue by crabdancing** [fabric-community/Composing#4] opened 2020-07-14 21:40 UTC
Crash occurred when I was flipping through pages of REI. It seems to happen every time in my modpack.

See crash log [here](https://paste.ee/p/b6kzY).

**Comment by Martmists-GH** [comment] 2020-07-14 21:59
Closing as duplicate of #2

**Closed as completed by Martmists-GH** 2020-07-14 21:59 UTC
Labels: duplicate
